# Generated by Django 4.0.5 on 2023-04-01 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transactiontype_income_type_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
    ]
