# Generated by Django 4.0.5 on 2023-04-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='income',
            name='wallet',
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='IncomeCategory',
        ),
    ]
