# Generated by Django 4.0.5 on 2023-04-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_wallet_name_alter_wallet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
