# Generated by Django 4.0.5 on 2023-04-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_category_name_cs_category_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='name_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='name_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
